data:
  chemical_path: "..." # The path of yangtze_antibiotics_ngg.xlsx 
  metal_path: "..."
  arg_path: "..."
  shannon_path: "..."
  ecological_path: "..."
  output_dir: "..."

preprocessing:
  remove_outliers: true   # Remove extreme outliers using PCA + Isolation Forest
  log_transform: true     # Apply log transformation to normalize data
  min_max_scaling: true   # Scale all independent variables to [0,1] range
  epsilon: 0.0000001      # Small constant to avoid log(0) issues
  pca_components: 4       
  feature_z_threshold: 3  
  contamination: 0.08      

feature_selection:
  method: "rfe"           
  top_n_chemicals: 20     
  top_n_metals: 10        
  top_n_ecological: 5     

clustering:
  method: "pca"           # Use PCA for clustering
  n_components: 2         # Reduce to 2 principal components for visualization
  plot: true              # Save PCA clustering plot

causal_analysis:
  method: "causalDML"     # Use Double Machine Learning (DML) for causal inference
  random_state: 42
  model_y:
    n_estimators: 100
    max_depth: 10
  model_t:
    n_estimators: 100

shap_analysis:
  max_display: 20         # Number of top SHAP features to display
  interaction_index: null  

correlation_analysis:
  importance_threshold: 0.02  # Minimum importance score for a feature
  correlation_threshold: 0.5  # Absolute correlation threshold for inclusion in network
  shap_threshold: 0.05        # Minimum SHAP value for inclusion in analysis
  pval_alpha: 0.05            # P-value cutoff for statistical significance

network_analysis:
  method: "spearman"       
  edge_weight_threshold: 0.1  
  top_n_nodes: 50          
  save_plots: true         

visualization:
  figsize: [20, 15]        
  layout: "kamada_kawai"   # Layout options: 'spring', 'circular', 'kamada_kawai'
  save_pca: true           
  save_shap: true          
  save_causal: true        

evaluation:
  cross_validation_folds: 10  
  scoring_metrics: ["r2", "rmse"]  
